apiVersion: v1
kind: PersistentVolume
metadata:
  name: broker-pv-1
  labels:
    type: broker-1
spec:
  capacity:
    storage: 20Gi
  accessModes:
  - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: vol-01f901b859600195a
    fsType: ext4
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: broker-pvc-1
  labels:
    type: broker-1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

