apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: mongo
  name: mongo-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: mongo
    spec:
      nodeSelector: 
        failure-domain.beta.kubernetes.io/zone: ap-northeast-1c
      containers:
      - image: mongo
        name: mongo
        args:
        - --auth
        ports:
        - name: mongo
          containerPort: 27017
          hostPort: 27017
        volumeMounts:
            - name: mongo-ebs-storage
              mountPath: /data/db
      volumes:
      - name: mongo-ebs-storage
        awsElasticBlockStore:
          volumeID: vol-027a31a6c489ba6d4
          fsType: ext4
            
---

apiVersion: v1
kind: Service
metadata:
  labels:
    name: mongo
  name: mongo
spec:
  type: NodePort
  ports:
    - port: 27017
      targetPort: 27017
      nodePort: 31000
  selector:
    name: mongo